"""Enable the PostGIS extension before any geometry columns are created.

Committed so that a fresh database (CI test DB, a new dev machine, or prod)
gets the `postgis` extension via `migrate`, rather than relying on a manual
`CREATE EXTENSION`. The model migration generated by `makemigrations core`
depends on this one automatically.
"""
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # Idempotent: emits `CREATE EXTENSION IF NOT EXISTS postgis`.
        CreateExtension("postgis"),
    ]
